Feature/tabs menu
Vizzuality/care-international pull request #16
Opened 2019-03-12 10:20 UTC by mluena

- Styles in impact sidebar

2019-03-12 10:35 UTC, andresgnlez commented on app/components/elements/AreaSummary/style.scss
> +      display: flex;
Not necessary. It already inherits it from `area-summary-wrapper`.

2019-03-15 11:39 UTC, andresgnlez commented on app/components/areas/Sidebar/Reach.jsx
>      const maxValue = Math.max.apply(null, programs.map((p) => {
Move it to a selector.

2019-03-19 15:44 UTC, mluena commented on app/components/areas/Sidebar/Reach.jsx
>      const maxValue = Math.max.apply(null, programs.map((p) => {
there is no redux in this project

2019-03-20 09:14 UTC, mbarrenechea requested changes

2019-03-20 09:14 UTC, mbarrenechea commented on app/components/elements/AreaSummary/index.jsx
> +            {programs.find((p) => p.id === program).label}
What would happen if we don't find anything? I can tell you, ERROR

2019-03-20 09:14 UTC, mbarrenechea commented on app/components/elements/AreaSummary/index.jsx
> +        <div className={classname(
```suggestion
        <div className={classname({
          'area-summary-wrapper': true,
          'impact': !location.href.includes("reach"),
          'reach': location.href.includes("reach")
        })
```

2019-03-20 11:32 UTC, mbarrenechea approved these changes

2019-03-20 11:32 UTC, merged